name: deployment
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a shell script
        env:
          GIT_USER_NAME: Mario Carlos Chita
        run: echo "$GIT_USER_NAME"