name: deployment
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  Check repository 
        uses: actions/checkout@v4
      - name: Run a shell script 
        env:
          GIT_USER: ${{vars.GIT_USER_OWNER }}
        run: echo "$GIT_USER"